"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const { generateFacmapSvg, defaultData } = require("./facmap_gen.js");

const htmlPath = path.join(__dirname, "..", "database", "factions.html");
const html = fs.readFileSync(htmlPath, "utf8");
const dataMatch = html.match(/<!-- FACMAP:DATA (.*?) -->/);
const svgMatch = html.match(/<svg class="facmap"[\s\S]*?<\/svg>/);

assert(dataMatch, "FACMAP:DATA comment was not found");
assert(svgMatch, "generated facmap SVG was not found");

const data = JSON.parse(dataMatch[1]);
const dataBefore = JSON.stringify(data);
assert.strictEqual(
  generateFacmapSvg(data),
  svgMatch[0],
  "JavaScript SVG differs from the SVG generated by Python"
);
assert.strictEqual(JSON.stringify(data), dataBefore, "generateFacmapSvg mutated its input data");
assert.strictEqual(
  generateFacmapSvg(defaultData),
  svgMatch[0],
  "bundled JavaScript default data differs from the current Python defaults"
);

console.log(`PASS: JavaScript and Python SVG are byte-identical (${Buffer.byteLength(svgMatch[0], "utf8")} UTF-8 bytes, ${data.hexes.length} hexes)`);
